import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'cms_language';

const messages = {
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_signin: 'Sign In',
    nav_language: 'Language',
    nav_bw_title: 'Toggle black and white mode',
    dashboard_menu: 'Menu',
    dashboard_panel: 'Panel',
    dashboard_signout: 'Sign Out',
    login_welcome: 'Welcome back',
    login_select_panel: 'Select your panel and sign in with your institutional account.',
    login_email: 'Email address',
    login_password: 'Password',
    login_signin: 'Sign In',
    login_signing_in: 'Signing in…',
    login_forgot: 'Forgot password?',
    login_back_signin: 'Back to sign in',
    login_forgot_title: 'Forgot Password',
    login_forgot_sub: 'Enter your registered email to receive a password reset link.',
    login_send_reset: 'Send reset link',
    login_sending_reset: 'Sending reset link…',
    login_reset_title: 'Reset Password',
    login_reset_sub: 'Set a new password for your account.',
    login_new_password: 'New password',
    login_confirm_password: 'Confirm password',
    login_reset_btn: 'Reset password',
    login_resetting: 'Resetting password…',
    // Home Page
    home_hero_badge: '🎓 Shah College',
    home_hero_title: 'Manage Your Institution Effortlessly',
    home_hero_span: 'Institution',
    home_hero_desc: 'A comprehensive, all-in-one platform for managing courses, students, teachers, attendance, assignments, and results — designed for educational institutions.',
    home_get_started: 'Get Started ←',
    home_learn_more: 'Learn More',
    home_features_title: 'Everything You Need',
    home_features_desc: 'Powerful features designed to simplify academic management and enhance the learning experience.',
    feature_course_title: 'Course Management',
    feature_course_desc: 'Create and manage courses, sections, and academic offerings with a comprehensive curriculum builder.',
    feature_enroll_title: 'Student Enrollment',
    feature_enroll_desc: 'Streamlined registration workflows with approval-based enrollment and real-time status tracking.',
    feature_assign_title: 'Assignments & Quizzes',
    feature_assign_desc: 'Teachers can create, distribute, and grade assignments with file upload and inline feedback support.',
    feature_attend_title: 'Attendance Tracking',
    feature_attend_desc: 'Mark and monitor daily attendance with detailed analytics and attendance percentage reports.',
    feature_result_title: 'Results & Grading',
    feature_result_desc: 'End-to-end results workflow with teacher submission and admin approval before publishing.',
    feature_role_title: 'Role-Based Access',
    feature_role_desc: 'Secure multi-role system — Admins, Teachers, and Students each have tailored dashboards and permissions.',
    home_quick_access_title: 'Smart Quick Access',
    home_quick_access_desc: 'Jump into the right module in one click based on your role and workflow.',
    home_info_banner_new: 'New:',
    home_info_banner_text: 'Admissions and onboarding workflows can be managed from the admin dashboard with status tracking.',
    home_stats_students: 'Students Managed',
    home_stats_courses: 'Courses Offered',
    home_stats_teachers: 'Expert Teachers',
    home_stats_uptime: 'System Uptime',
    home_gallery_title: 'Our Campus',
    home_gallery_desc: 'Explore the vibrant learning environment that inspires excellence and innovation.',
    gallery_entrance: 'Campus Entrance',
    gallery_library: 'Library Block',
    gallery_sports: 'Sports Ground',
    gallery_classroom: 'Classroom',
    gallery_lab: 'Lab Facilities',
    gallery_auditorium: 'Auditorium',
    home_faq_title: 'Frequently Asked Questions',
    home_faq_desc: 'Quick answers to common queries from admins, teachers, and students.',
    home_faq_search: 'Search a question...',
    home_faq_empty: 'No matching questions found.',
    home_cta_title: 'Ready to Transform Your Institution?',
    home_cta_desc: 'Join hundreds of educational organizations already using Shah College to streamline their operations.',
    home_cta_btn: 'Sign In to Dashboard ←',
    home_footer_rights: 'All rights reserved.',
    // FAQs
    faq_q1: 'Can we use this for multiple departments?',
    faq_a1: 'Yes. Shah College supports department-wise course and teacher management with role-based access.',
    faq_q2: 'Do teachers need technical training to use it?',
    faq_a2: 'No. The teacher dashboard is designed for daily academic workflows with simple forms and guided actions.',
    faq_q3: 'How are results published?',
    faq_a3: 'Teachers submit marks and admins approve them before students can view final results.',
    faq_q4: 'Is attendance tracking available by class?',
    faq_a4: 'Yes. Teachers can mark attendance per class session and view summary percentages instantly.',
    // About Page
    about_hero_title: 'About Shah College',
    about_hero_desc: "We're building the future of academic management — a platform that empowers institutions to focus on what matters most: education.",
    about_val_mission_title: 'Our Mission',
    about_val_mission_desc: 'To provide educational institutions with a powerful, intuitive management platform that simplifies academic operations and enhances collaboration between administrators, teachers, and students.',
    about_val_vision_title: 'Our Vision',
    about_val_vision_desc: 'To become the leading college management solution trusted by institutions worldwide, setting the standard for digital academic excellence and operational efficiency.',
    about_val_approach_title: 'Our Approach',
    about_val_approach_desc: 'We believe in building tools that are both powerful and easy to use. Every feature is designed with real-world academic workflows in mind, ensuring seamless adoption and immediate productivity gains.',
    about_why_choose: 'Why Choose Us',
    about_why_desc: 'Built with reliable technology and designed for real academic workflows.',
    about_high_multi_title: 'Multi-Department Support',
    about_high_multi_desc: 'Manage multiple departments, programs, and year levels from a single unified platform.',
    about_high_resp_title: 'Fully Responsive',
    about_high_resp_desc: 'Access the system from any device — desktop, tablet, or smartphone with a consistent experience.',
    about_high_secure_title: 'Secure & Reliable',
    about_high_secure_desc: 'Built with enterprise-grade security practices including role-based access control and encrypted sessions.',
    about_high_stats_title: 'Real-time Analytics',
    about_high_stats_desc: 'Track attendance, performance, and enrollment trends with live dashboard analytics and reporting.',
    about_leadership: 'Leadership Team',
    about_leadership_desc: 'Meet the people behind Shah College who are passionate about transforming education.',
  },
  ur: {
    nav_home: 'ہوم',
    nav_about: 'تعارف',
    nav_signin: 'لاگ اِن',
    nav_language: 'زبان',
    nav_bw_title: 'بلیک/وائٹ موڈ تبدیل کریں',
    dashboard_menu: 'مینو',
    dashboard_panel: 'پینل',
    dashboard_signout: 'لاگ آؤٹ',
    login_welcome: 'خوش آمدید',
    login_select_panel: 'اپنا پینل منتخب کریں اور اپنے ادارہ جاتی اکاؤنٹ سے لاگ اِن کریں۔',
    login_email: 'ای میل',
    login_password: 'پاس ورڈ',
    login_signin: 'لاگ اِن',
    login_signing_in: 'لاگ اِن ہو رہا ہے…',
    login_forgot: 'پاس ورڈ بھول گئے؟',
    login_back_signin: 'واپس لاگ اِن',
    login_forgot_title: 'پاس ورڈ بھول گئے',
    login_forgot_sub: 'ری سیٹ لنک حاصل کرنے کے لیے اپنا رجسٹرڈ ای میل درج کریں۔',
    login_send_reset: 'ری سیٹ لنک بھیجیں',
    login_sending_reset: 'ری سیٹ لنک بھیجا جا رہا ہے…',
    login_reset_title: 'پاس ورڈ ری سیٹ',
    login_reset_sub: 'اپنے اکاؤنٹ کے لیے نیا پاس ورڈ درج کریں۔',
    login_new_password: 'نیا پاس ورڈ',
    login_confirm_password: 'پاس ورڈ کی تصدیق',
    login_reset_btn: 'پاس ورڈ ری سیٹ کریں',
    login_resetting: 'پاس ورڈ ری سیٹ ہو رہا ہے…',
    // Home Page
    home_hero_badge: '🎓 شاہ کالج',
    home_hero_title: 'اپنے ادارے کا انتظام آسانی سے سنبھالیں',
    home_hero_span: 'ادارے',
    home_hero_desc: 'کورسز، طلباء، اساتذہ، حاضری، اسائنمنٹس اور نتائج کے انتظام کے لیے ایک مکمل پلیٹ فارم — جو تعلیمی اداروں کے لیے ڈیزائن کیا گیا ہے۔',
    home_get_started: 'شروع کریں ←',
    home_learn_more: 'مزید جانیں',
    home_features_title: 'وہ سب کچھ جو آپ کو چاہیے',
    home_features_desc: 'تعلیمی انتظام کو بہتر بنانے کے لیے ڈیزائن کردہ طاقتور خصوصیات۔',
    feature_course_title: 'کورس مینجمنٹ',
    feature_course_desc: 'ایک جامع نصاب بلڈر کے ساتھ کورسز، گروپس اور تعلیمی پیشکشوں کا انتظام کریں۔',
    feature_enroll_title: 'طلباء کا داخلہ',
    feature_enroll_desc: 'منظوری کی بنیاد پر رجسٹریشن اور ریئل ٹائم اسٹیٹس ٹریکنگ کے ساتھ داخلے کا عمل۔',
    feature_assign_title: 'اسائنمنٹس اور کوئز',
    feature_assign_desc: 'اساتذہ اسائنمنٹس بنا سکتے ہیں، تقسیم کر سکتے ہیں اور آن لائن فیڈ بیک کے ساتھ گریڈ دے سکتے ہیں۔',
    feature_attend_title: 'حاضری ٹریکنگ',
    feature_attend_desc: 'تفصیلی تجزیات اور فیصد رپورٹوں کے ساتھ روزانہ کی حاضری کی نگرانی کریں۔',
    feature_result_title: 'نتائج اور گریڈنگ',
    feature_result_desc: 'نتائج کا مکمل عمل — اساتذہ کی جمع کروائی گئی مارکس شیٹ اور ایڈمن کی منظوری۔',
    feature_role_title: 'رول بیسڈ رسائی',
    feature_role_desc: 'محفوظ ملٹی رول سسٹم — ایڈمن، اساتذہ اور طلباء کے لیے مخصوص ڈیش بورڈز۔',
    home_quick_access_title: 'سمارٹ فوری رسائی',
    home_quick_access_desc: 'اپنے رول اور کام کے مطابق ایک کلک میں متعلقہ ماڈیول تک پہنچیں۔',
    home_info_banner_new: 'نیا:',
    home_info_banner_text: 'ایڈمن ڈیش بورڈ سے اب داخلہ اور آن بورڈنگ کا عمل ٹریکنگ کے ساتھ سنبھالا جا سکتا ہے۔',
    home_stats_students: 'طلباء',
    home_stats_courses: 'کورسز',
    home_stats_teachers: 'ماہر اساتذہ',
    home_stats_uptime: 'سسٹم اپ ٹائم',
    home_gallery_title: 'ہمارا کیمپس',
    home_gallery_desc: 'ایک بہترین تعلیمی ماحول جو جدت اور مہارت کو فروغ دیتا ہے۔',
    gallery_entrance: 'کیمپس کا داخلی راستہ',
    gallery_library: 'لائبریری بلاک',
    gallery_sports: 'کھیل کا میدان',
    gallery_classroom: 'کلاس روم',
    gallery_lab: 'لیبارٹری کی سہولیات',
    gallery_auditorium: 'آڈیٹوریم',
    home_faq_title: 'اکثر پوچھے گئے سوالات',
    home_faq_desc: 'ایڈمن، اساتذہ اور طلباء کے عام سوالات کے فوری جوابات۔',
    home_faq_search: 'سوال تلاش کریں...',
    home_faq_empty: 'کوئی سوال نہیں ملا۔',
    home_cta_title: 'کیا آپ اپنے ادارے کو ڈیجیٹل کرنے کے لیے تیار ہیں؟',
    home_cta_desc: 'سیکڑوں ادارے پہلے ہی شاہ کالج کا استعمال کر رہے ہیں۔ آج ہی شامل ہوں۔',
    home_cta_btn: 'ڈیش بورڈ پر لاگ ائن کریں ←',
    home_footer_rights: 'جملہ حقوق محفوظ ہیں۔',
    // FAQs
    faq_q1: 'کیا ہم اسے متعدد محکموں کے لیے استعمال کر سکتے ہیں؟',
    faq_a1: 'جی ہاں۔ شاہ کالج رول بیسڈ رسائی کے ساتھ ڈپارٹمنٹ وائز کورس اور ٹیچر مینجمنٹ کو سپورٹ کرتا ہے۔',
    faq_q2: 'کیا اساتذہ کو اسے استعمال کرنے کے لیے تکنیکی تربیت کی ضرورت ہے؟',
    faq_a2: 'نہیں۔ ٹیچر ڈیش بورڈ روزانہ کے تعلیمی کاموں کے لیے سادہ فارمز اور گائیڈڈ ایکشنز کے ساتھ ڈیزائن کیا گیا ہے۔',
    faq_q3: 'نتائج کیسے شائع ہوتے ہیں؟',
    faq_a3: 'اساتذہ نمبر جمع کرواتے ہیں اور طلباء کے فائنل نتائج دیکھنے سے پہلے ایڈمن ان کی منظوری دیتے ہیں۔',
    faq_q4: 'کیا کلاس کے لحاظ سے حاضری ٹریکنگ دستیاب ہے؟',
    faq_a4: 'جی ہاں۔ اساتذہ فی کلاس سیشن حاضری لگا سکتے ہیں اور فوری طور پر فیصد دیکھ سکتے ہیں۔',
    // About Page
    about_hero_title: 'شاہ کالج کے بارے میں',
    about_hero_desc: 'ہم تعلیمی انتظام کے مستقبل کی تعمیر کر رہے ہیں — ایک ایسا پلیٹ فارم جو اداروں کو ان کے اصل مقصد، یعنی تعلیم، پر توجہ دینے کی طاقت دیتا ہے۔',
    about_val_mission_title: 'ہمارا مشن',
    about_val_mission_desc: 'تعلیمی اداروں کو ایک طاقتور، بدیہی مینجمنٹ پلیٹ فارم فراہم کرنا جو تعلیمی کاموں کو آسان بناتا ہے۔',
    about_val_vision_title: 'ہمارا وژن',
    about_val_vision_desc: 'دنیا بھر کے اداروں کے ذریعہ قابل بھروسہ کالج مینجمنٹ حل بننا۔',
    about_val_approach_title: 'ہمارا طریقہ کار',
    about_val_approach_desc: 'ہم ایسے ٹولز بنانے پر یقین رکھتے ہیں جو طاقتور اور استعمال میں آسان ہوں۔',
    about_why_choose: 'ہمارا انتخاب کیوں؟',
    about_why_desc: 'قابل بھروسہ ٹیکنالوجی کے ساتھ تیار کردہ، جو حقیقی تعلیمی کاموں کے لیے ڈیزائن کی گئی ہے۔',
    about_high_multi_title: 'ملٹی ڈپارٹمنٹ سپورٹ',
    about_high_multi_desc: 'ایک ہی پلیٹ فارم سے متعدد محکموں اور پروگراموں کا انتظام کریں۔',
    about_high_resp_title: 'مکمل طور پر ریسپونسیو',
    about_high_resp_desc: 'کسی بھی ڈیوائس — ڈیسک ٹاپ، ٹیبلٹ، یا اسمارٹ فون سے سسٹم تک رسائی حاصل کریں۔',
    about_high_secure_title: 'محفوظ اور قابل بھروسہ',
    about_high_secure_desc: 'انٹرپرائز گریڈ سیکیورٹی پریکٹسز کے ساتھ بنایا گیا رول بیسڈ سسٹم۔',
    about_high_stats_title: 'ریئل ٹائم اینالیٹکس',
    about_high_stats_desc: 'لائیو ڈیش بورڈ اینالیٹکس کے ساتھ حاضری اور کارکردگی کو ٹریک کریں۔',
    about_leadership: 'قیادت کی ٹیم',
    about_leadership_desc: 'شاہ کالج کے پیچھے ان لوگوں سے ملیں جو تعلیم کی تبدیلی کے لیے پرجوش ہیں۔',
  },
  hi: {
    nav_home: 'होम',
    nav_about: 'परिचय',
    nav_signin: 'साइन इन',
    nav_language: 'भाषा',
    nav_bw_title: 'ब्लैक/व्हाइट मोड बदलें',
    dashboard_menu: 'मेनू',
    dashboard_panel: 'पैनल',
    dashboard_signout: 'साइन आउट',
    login_welcome: 'वापसी पर स्वागत है',
    login_select_panel: 'अपना पैनल चुनें और अपने संस्थान खाते से साइन इन करें।',
    login_email: 'ईमेल पता',
    login_password: 'पासवर्ड',
    login_signin: 'साइन इन',
    login_signing_in: 'साइन इन हो रहा है…',
    login_forgot: 'पासवर्ड भूल गए?',
    login_back_signin: 'साइन इन पर वापस जाएं',
    login_forgot_title: 'पासवर्ड भूल गए',
    login_forgot_sub: 'रीसेट लिंक पाने के लिए अपना रजिस्टर्ड ईमेल डालें।',
    login_send_reset: 'रीसेट लिंक भेजें',
    login_sending_reset: 'रीसेट लिंक भेजा जा रहा है…',
    login_reset_title: 'पासवर्ड रीसेट',
    login_reset_sub: 'अपने खाते के लिए नया पासवर्ड सेट करें।',
    login_new_password: 'नया पासवर्ड',
    login_confirm_password: 'पासवर्ड की पुष्टि करें',
    login_reset_btn: 'पासवर्ड रीसेट करें',
    login_resetting: 'पासवर्ड रीसेट हो रहा है…',
    // Home Page
    home_hero_badge: '🎓 शाह कॉलेज',
    home_hero_title: 'अपने संस्थान का प्रबंधन आसानी से करें',
    home_hero_span: 'संस्थान',
    home_hero_desc: 'पाठ्यक्रम, छात्रों, शिक्षकों, उपस्थिति, असाइनमेंट और परिणामों के प्रबंधन के लिए एक व्यापक मंच।',
    home_get_started: 'शुरू करें ←',
    home_learn_more: 'अधिक जानें',
    home_features_title: 'वो सब जो आपको चाहिए',
    home_features_desc: 'शैक्षिक प्रबंधन को सरल बनाने के लिए डिज़ाइन की गई शक्तिशाली विशेषताएं।',
    home_quick_access_title: 'स्मार्ट त्वरित पहुँच',
    home_quick_access_desc: 'अपनी भूमिका के आधार पर एक क्लिक में सही मॉड्यूल पर जाएं।',
    home_info_banner_new: 'नया:',
    home_info_banner_text: 'प्रवेश और ऑनबोर्डिंग वर्कफ़्लो को अब एडमिन डैशबोर्ड से प्रबंधित किया जा सकता है।',
    home_stats_students: 'छात्र',
    home_stats_courses: 'पाठ्यक्रम',
    home_stats_teachers: 'विशेषज्ञ शिक्षक',
    home_stats_uptime: 'सिस्टम अपटाइम',
    home_gallery_title: 'ہمارا کیمپس',
    home_gallery_desc: 'एक उत्कृष्ट शिक्षण वातावरण जो नवाचार को प्रेरित करता है।',
    home_faq_title: 'अक्सर पूछे जाने वाले प्रश्न',
    home_faq_desc: 'एडमिन, शिक्षकों और छात्रों के सामान्य प्रश्नों के त्वरित उत्तर।',
    home_faq_search: 'प्रश्न खोजें...',
    home_faq_empty: 'कोई प्रश्न नहीं मिला।',
    home_cta_title: 'क्या आप अपने संस्थान को बदलने के लिए तैयार हैं?',
    home_cta_desc: 'सैकड़ों संस्थान पहले से ही शाह कॉलेज का उपयोग कर रहे हैं।',
    home_cta_btn: 'डैशबोर्ड पर साइन इन करें ←',
    home_footer_rights: 'सर्वाधिकार सुरक्षित।',
    // About Page
    about_hero_title: 'शाह कॉलेज के बारे में',
    about_hero_desc: 'हम शैक्षणिक प्रबंधन کے مستقبل کی تعمیر کر رہے ہیں — एक ऐसा मंच जो संस्थानों को सशक्त बनाता है।',
    about_why_choose: 'हमें क्यों चुनें',
    about_why_desc: 'भरोसेमंद तकनीक के साथ निर्मित, वास्तविक शैक्षणिक वर्कफ़्लो के लिए डिज़ाइन किया गया।',
    about_leadership: 'नेतृत्व टीम',
    about_leadership_desc: 'उन लोगों से मिलें जो शिक्षा को बदलने के लिए समर्पित हैं।',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en');

  useEffect(() => {
    if (!['en', 'ur', 'hi'].includes(lang)) {
      setLang('en');
      return;
    }
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang;
    // Removed global RTL toggle to satisfy user preference for LTR layout with translations
    // document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    setLang,
    t: (key, fallback = '') => messages[lang]?.[key] || fallback || key,
  }), [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
